main/website/routers/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from .. import forms, db
from flask_login import login_user, login_required, logout_user, current_user
from ..models import User, AccountRecovery

auth = Blueprint('auth',__name__)

@auth.route("/login", methods=["GET","POST"])
def login_account():
    form = forms.LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user)
                return redirect(url_for("properties_views.map_page"))
            else:
                flash('Incorrect email or password', category='error')
        else:
            flash('Incorrect email or password', category='error')
        
    return render_template("login_page.html", user=current_user, form=form)

@auth.route("/logout")
@login_required
def logout_account():
    logout_user()
    return redirect(url_for("auth.login_account"))

@auth.route("/register", methods=["GET","POST"])
def register_account():
    form = forms.RegistrationForm()
    if form.validate_on_submit():
        email = form.email.data
        user = User.query.filter_by(email=email).first()
        if user:
            flash("Email: Email is already taken",category='error')
        else:
            password = generate_password_hash(form.password.data) #123456789aA$ , 123456789aA$$

            new_user = User(email=email, 
                            password=password, 
                            username=email.split("@")[0], 
                            account_type=form.register_as.data,
                            first_name=form.first_name.data,
                            last_name=form.last_name.data)
            
            User.register_account(new_user)

            flash(f"Registered as a {str(form.register_as.data).title()} Successfully", category='success')
            return redirect(url_for('auth.login_account'))
        
    return render_template("register_account_page.html", user=current_user, form=form)

@auth.route('/forgetpassword', methods=['GET', 'POST'])
def forget_password_request():
    form = forms.ForgetPasswordForm()
    if form.validate_on_submit():
        email = form.email.data
        user = User.query.filter_by(email=email).first()

        if user:
            flash_msg = AccountRecovery.create_and_send_account_recovery(user, request.url_root)

            flash(flash_msg[0], flash_msg[1])

            return redirect(url_for("auth.login_account"))
        else:
            flash("There are no accounts with this email", 'error')
            return redirect(url_for("auth.forget_password_request"))
        
    return render_template("forget_password_request_page.html", user=current_user, form=form)


@auth.route('/forgetpassword/<uuid:reset_id>', methods=["GET", "POST"])
def forget_password(reset_id):
    form = forms.ChangeForgetPasswordForm()

    valid_request = AccountRecovery.check_valid_recovery_string(str(reset_id))

    if not valid_request[0]:
        flash(valid_request[1], valid_request[2])
        return redirect(url_for("auth.forget_password_request"))
    else:
        if form.validate_on_submit():
            account_recovery = valid_request[1]
            user_id = account_recovery.user_id
            user = User.query.filter_by(user_id=user_id).first()

            password = generate_password_hash(form.password.data)
            user.password = password

            db.session.delete(account_recovery)

            db.session.commit()
            flash("Password changed successfully")
            return redirect(url_for("auth.login_account"))
    return render_template("forget_password_change_page.html", user=current_user, form=form, reset_id=reset_id)

@auth.route('/page404')
def page404():
    return render_template("404.html", user=current_user)

main/website/routers/views.py
import os.path

from flask import Blueprint, render_template, url_for, flash, redirect, request, current_app
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename

from .custom_decorators import landlord_required
from .. import forms, db, models
from ..models import Property, PropertyImages, Notifications, User
from datetime import datetime
import requests
from werkzeug.security import check_password_hash


views = Blueprint('views', __name__)

@views.route("/")
def landing_page():
    latest_properties = Property.query.filter_by(is_approved=1).order_by(Property.created_at.desc()).limit(3).all()

    return render_template("landing_page.html", user=current_user, latest_properties=latest_properties, datetime_now = datetime.now())


APPROVAL_FORM_ALLOWED_EXTENSIONS = {"pdf"}
IMAGES_ALLOWED_EXTENSIONS = {"png"}


def allowed_file(filename, allowed_extensions):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in allowed_extensions

@views.route("/manage_property/approved")
@login_required
@landlord_required
def manage_property_approved():
    # get all properties owned by user
    property_list = db.paginate(db.select(Property).where(Property.user_id == current_user.user_id, Property.is_approved==True).order_by(Property.created_at.desc()), per_page=10)
    if request.args.get('page'):
        property_list = db.paginate(db.select(Property).where(Property.user_id == current_user.user_id, Property.is_approved==True).order_by(Property.created_at.desc()), per_page=10, page=int(request.args.get('page')))
    print(property_list)
    return render_template("manage_property_page.html", user=current_user, property_list=property_list, approved=True, deletion=False)

@views.route("/manage_property/unapproved")
@login_required
@landlord_required
def manage_property_unapproved():
    # get all properties owned by user
    property_list = db.paginate(db.select(Property).where(Property.user_id == current_user.user_id, Property.is_approved==False).order_by(Property.created_at.desc()), per_page=10)
    if request.args.get('page'):
        property_list = db.paginate(db.select(Property).where(Property.user_id == current_user.user_id, Property.is_approved==False).order_by(Property.created_at.desc()), per_page=10, page=int(request.args.get('page')))

    return render_template("manage_property_page.html", user=current_user, property_list=property_list, approved=False, deletion=False)


@views.route("/manage_property/pending_deletion")
@login_required
@landlord_required
def manage_property_pending_deletion():
    # get all properties owned by user
    property_list = db.paginate(db.select(Property).where(Property.user_id == current_user.user_id, Property.is_pending_deletion==True).order_by(Property.created_at.desc()), per_page=10)
    if request.args.get('page'):
        property_list = db.paginate(db.select(Property).where(Property.user_id == current_user.user_id, Property.is_pending_deletion==True).order_by(Property.created_at.desc()), per_page=10, page=int(request.args.get('page')))

    return render_template("manage_property_page.html", user=current_user, property_list=property_list, approved=False, deletion=True)

@views.route("/manage_property/registerproperty", methods=["GET", "POST"])
@login_required
@landlord_required
def register_property():
    form = forms.RegisterPropertyForm()

    if form.validate_on_submit():
        # check if the approval form is the correct type
        approval_form_filename = secure_filename(form.approval_form.name)  # get the file name from the form
        approval = request.files[approval_form_filename]  # get the filestorage object

        if approval.filename == "":  # empty file name, no file selected
            flash("No approval file selected", "error")
            return redirect(url_for('views.register_property'))

        if not allowed_file(approval.filename, APPROVAL_FORM_ALLOWED_EXTENSIONS):  # check if file is pdf type
            flash("Invalid approval file type, only .pdf files are allowed", "error")
            return redirect(url_for('views.register_property'))

        # do the same check for image(multiple images can be uploaded)
        for i, image in enumerate(form.image.data):
            if i > 5:
                flash("Max of 5 images are allowed", "error")
                return redirect(url_for('views.register_property'))

            if not allowed_file(secure_filename(image.filename),
                                IMAGES_ALLOWED_EXTENSIONS):  # check if file is png type
                flash("Invalid image file type, only .png files are allowed", "error")
                return redirect(url_for('views.register_property'))

        postal_code = form.postal_code.data
        url = f"https://www.onemap.gov.sg/api/common/elastic/search?searchVal={postal_code}&returnGeom=Y&getAddrDetails=Y&pageNum=1"
        response = requests.request("GET", url)
        response = response.json()
        # sanity check, if the response["results"] has length 0, it means no address is returned
        if len(response["results"]) == 0:
            flash("Invalid postal code", "error")
            return redirect(url_for('views.register_property'))
        result_dict = response["results"][0]
        property_latitude = result_dict['LATITUDE']
        property_longitude = result_dict['LONGITUDE']
        property_streetname = result_dict['ROAD_NAME']
        property_building = result_dict['BUILDING'] #if result_dict['BUILDING'] != 'NIL' else result_dict['BLK_NO'] # some properties are using NIL as building name in the csv file, keep it as it is
        property_block = result_dict['BLK_NO']

        new_property = models.Property(user_id=current_user.user_id,
                                       #rent_approval_date=form.rent_approval_date.data, # set approval date only when admin approves
                                       town=form.town.data,
                                       block=property_block,
                                       street_name=property_streetname,
                                       flat_type=form.flat_type.data,
                                       monthly_rent=form.monthly_rent.data,
                                       postal=form.postal_code.data,
                                       latitude=property_latitude,
                                       longitude=property_longitude,
                                       building=property_building,
                                       number_of_bedrooms=form.num_bedrooms.data,
                                       floorsize=form.floor_size.data,
                                       price_per_square_metre=round(form.monthly_rent.data / form.floor_size.data, 6),
                                       year_built=form.year_built.data,
                                       floor_level=form.floor_level.data,
                                       furnishing=form.furnishing.data,
                                       lease_term=form.lease_term.data,
                                       negotiable_pricing=form.negotiable.data,
                                       property_name=form.property_name.data,
                                       property_description=form.property_description.data,
                                       gender=form.gender.data)
        db.session.add(new_property)
        db.session.commit()
        db.session.refresh(new_property)

        property_id = new_property.property_id

        reformatted_filename = f"{property_id}"

        # save the approval form to the respective folder
        approval_form_file_path = os.path.join(current_app.config["APPROVAL_DOCUMENT_UPLOAD_FOLDER"], reformatted_filename + ".pdf")
        approval.save(approval_form_file_path)
        new_property.approval_document_url = reformatted_filename + ".pdf"
        db.session.commit()

        # save the image(s) to the respective folder and add it into the property_image database
        # image_url in the property_image database will store all images separated by a comma
        for i, image in enumerate(form.image.data):
            image_form_file_path = os.path.join(current_app.config["IMAGE_UPLOAD_FOLDER"], reformatted_filename + f"_{i}.png")
            image.save(image_form_file_path)
            new_property_image = PropertyImages(property_id=property_id,
                                                image_url=reformatted_filename+f"_{i}.png")
            db.session.add(new_property_image)
            db.session.commit()
        flash("Property registered, pending approval", "success")
        return redirect(url_for('views.manage_property_unapproved'))

    return render_template("register_property.html", user=current_user, form=form)

@views.route("/manage_property/edit_property/<prop_id>", methods=["GET", "POST"])
@login_required
@landlord_required
def edit_property(prop_id):
    form = forms.EditProperty()
    # get the property with prop_id and prefill in the form with previous information
    current_property = Property.query.filter_by(property_id=prop_id).first()

    if request.method == "GET":
        # prefill the form
        form.property_name.data = current_property.property_name
        form.monthly_rent.data = current_property.monthly_rent
        form.num_bedrooms.data = current_property.number_of_bedrooms
        form.gender.data = current_property.gender
        form.furnishing.data = current_property.furnishing
        form.lease_term.data = current_property.lease_term
        form.negotiable.data = current_property.negotiable_pricing
        form.property_description.data = current_property.property_description
    else: # POST
        # edit property
        if form.validate_on_submit() and form.edit_property_button.data:

            # redirect user if wrong password
            if not check_password_hash(current_user.password, form.confirm_password.data):

main/website/templates/account_settings.html
{% extends "includes/layout.html" %}

{% block title %}Account Settings{% endblock title %}

{% block page_name %}
Account Settings
{% endblock page_name %}

{% block content %}
{% from "includes/formhelper.html" import render_field %}
{% if setting_type and form.errors %}
	{% for field_name, field_errors in form.errors|dictsort if field_errors %}
		{% for error in field_errors %}
		<div class="alert alert-danger alert-dismissible fade show" role="alert">
			{{ form[field_name].label }}: {{ error }}
			<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		</div>
		{% endfor %}
	{% endfor %}
{% endif %}
<div class="container pt-4">
	<div class="row">
		<div class="col-sm-3">
			<a href='{{ url_for("account_views.account_settings", setting_type="account") }}' class="btn 
			{% if not setting_type or setting_type == 'password' %}
			btn-secondary
			{% else %}
			btn-info	
			{% endif %}
			">Change Username</a>
			<hr/>
			<a href='{{ url_for("account_views.account_settings", setting_type="password") }}' class="btn 
			{% if not setting_type or setting_type == 'account' %}
			btn-secondary
			{% else %}
			btn-info	
			{% endif %}">Change Password</a>
		</div>
		
		<div class="col-sm-8 offset-1">
			{% if setting_type == 'account' %}
			<form action="{{ url_for('account_views.account_settings', setting_type='account') }}" method="post">
				{{ form.csrf_token }}
				<div class="form-group">
					{{ render_field(form.username, class_="form-control", value=user.username) }}
				</div>
				<br>
				<div class="form-group">Confirm by entering your current
					{{ render_field(form.password, class_="form-control") }}
				</div>
				<br>
				<div>
					<input type="submit" class="btn btn-primary" value="Update Information">
				</div>
			</form>
			{% elif setting_type == 'password' %}
			<form action="{{ url_for('account_views.account_settings', setting_type='password') }}" method="post">
				{{ form.csrf_token }}
				<div class="form-group form-box">
					{{ render_field(form.current_password, class_="form-control") }}
				</div>
				<div class="form-group form-box">
					{{ render_field(form.new_password, class_="form-control") }}
				</div>
				<div class="form-group form-box">
					{{ render_field(form.confirm_new_password, class_="form-control") }}
				</div>
				<div class="form-group" style="padding-left: 20px;">
					<input type="submit" class="btn btn-primary" value="Change Password">
				</div>
			</form>
			{% endif %}
		</div>
	</div>
</div>
{% endblock content %}

main/website/templates/delete_property_page.html
{% extends "includes/layout.html" %}

{% block title %}Delete Property{% endblock title %}
{% block page_name %}
Delete Property
{% endblock page_name %}
{% block content %}
<div class="container pt-5">
    {% from "includes/formhelper.html" import render_field %}
    {% if form.errors %}
    {% for field_name, field_errors in form.errors|dictsort if field_errors %}
    {% for error in field_errors %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ form[field_name].label }}: {{ error }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endfor %}
    {% endif %}
    <div class="row">
        <div class="col-lg-6 offset-lg-3">
            <form action="{{ url_for('views.delete_property', prop_id=prop_id) }}" method="post">
                {{ form.csrf_token }}
                {% for field in form %}
                {% if field.type == 'StringField' or field.type == 'PasswordField' %}
                <div class="form-group">
                    {{ render_field(field, class_="form-control") }}
                </div>
                {% endif %}
                {% if field.type == 'SubmitField' %}
                {{ form.delete_field(class_="btn btn-danger") }}
                {% endif %}
                {% endfor %}        
            </form>
        </div>
    </div>
</div>
{% endblock content %}

main/website/templates/favourite_properties_page.html
{% extends "includes/layout.html" %}

{% block title %}Favourited Properties{% endblock title %}

{% block page_name %}
Favourited Properties
{% endblock page_name %}

{% block content %}
{% from "includes/formhelper.html" import render_field %}
<div class="container pt-5">
    {% if property_list %}
    {% for i in range(property_list|length) %}
    {% set property = property_list[i] %}
    {% set property_image = property_images[i] %}
    <div class="row pb-2">
        <div class="col-sm-4">
            <img src="{{ url_for('properties_views.property_image_url', filename=property_image.image_url) }}" class="img-fluid" alt="Responsive image">
        </div>
        <div class="col-sm-8">
            <div class="row">
                <div class="col-12">
                    <h2><a href="{{ url_for('properties_views.map_page_info',property_id=property.property_id) }}">{{ property.property_name }}</a>
                        <i value="{{property.property_id}}" class="favHeart fa-solid fa-heart" style="cursor: pointer;color:#df6951;"></i>
                    </h2>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <h3>${{ property.monthly_rent }}/month</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <p>{{ property.description }}</p>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <p>{{ property.block }} {{ property.street_name }} {{ property.building }}</p>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <p>Singapore {{ property.postal }}</p>
                </div>
            </div>
        </div>
    </div>     
    {% endfor %}
    {% else %}
    <div class="row">
        <div class="col-12">
            <h2 class="text-center">No favourites yet</h2>
        </div>
    </div>
    {% endif %}
    
</div>

{% endblock content %}

{% block bottomScript %}
<script>
    // favourite button
    $(".favHeart").on("click", function() {
        if (this.classList.contains("fa-regular")) {
            this.classList.remove("fa-regular");
            this.classList.add("fa-solid");
            favHeart.style.color = '#df6951';
        } else {
            this.classList.remove("fa-solid");
            this.classList.add("fa-regular");
            favHeart.style.color = '#df6951';
        }
        var property_id = this.getAttribute("value");
        var string = "/map/" + property_id + "/favourite";
        $.post(string, function(data, status) {
            console.log(data);
        });
        
    });
</script>
{% endblock bottomScript %}

main/website/templates/forget_password_change.html
{% extends "includes/layout.html" %}

{% block title %}Forget Password{% endblock title %}

{% block page_name %}
Change Your Password
{% endblock page_name %}

{% block content %}
	{% from "includes/formhelper.html" import render_field %}
	{% if form.errors %}
		{% for field_name, field_errors in form.errors|dictsort if field_errors %}
			{% for error in field_errors %}
			<div class="alert alert-danger alert-dismissible fade show" role="alert">
				{{ form[field_name].label }}: {{ error }}
				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
			{% endfor %}
		{% endfor %}
	{% endif %}
	<div class="container pt-5">
		<div class="row">
			<div class="col-lg-6 offset-lg-3">
				<form action="{{ url_for('auth.forget_password', reset_id=reset_id) }}" method="post">
				{{ form.csrf_token }}
				<div class="form-group form-box">
					{{ render_field(form.password, class_="form-control") }}
				</div>
				<div class="form-group form-box">
					{{ render_field(form.confirm_password, class_="form-control") }}
				</div>
				<div class="form=group text-center">
					<input type="submit" class="btn btn-primary" value="Change Password">
				</div>
			</form>
			</div>
		</div>
	</div>
{% endblock content %}

main/website/templates/forget_password_change_page.html
{% extends "includes/layout.html" %}

{% block title %}Forget Password{% endblock title %}

{% block page_name %}
Change Your Password
{% endblock page_name %}

{% block content %}
	{% from "includes/formhelper.html" import render_field %}
	{% if form.errors %}
		{% for field_name, field_errors in form.errors|dictsort if field_errors %}
			{% for error in field_errors %}
			<div class="alert alert-danger alert-dismissible fade show" role="alert">
				{{ form[field_name].label }}: {{ error }}
				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
			{% endfor %}
		{% endfor %}
	{% endif %}
	<div class="container pt-5">
		<div class="row">
			<div class="col-lg-6 offset-lg-3">
				<form action="{{ url_for('auth.forget_password', reset_id=reset_id) }}" method="post">
				{{ form.csrf_token }}
				<div class="form-group form-box">
					{{ render_field(form.password, class_="form-control") }}
				</div>
				<div class="form-group form-box">
					{{ render_field(form.confirm_password, class_="form-control") }}
				</div>
				<div class="form=group text-center">
					<input type="submit" class="btn btn-primary" value="Change Password">
				</div>
			</form>
			</div>
		</div>
	</div>
{% endblock content %}

main/website/templates/login_page.html
{% extends "includes/layout.html" %}

{% block title %}Login{% endblock title %}

{% block page_name %}
Login
{% endblock page_name %}

{% block content %}
<div class="container pt-5">
	{% from "includes/formhelper.html" import render_field %}
	{% if form.errors %}
	{% for field_name, field_errors in form.errors|dictsort if field_errors %}
	{% for error in field_errors %}
	<div class="alert alert-danger alert-dismissible fade show" role="alert">
		{{ form[field_name].label }}: {{ error }}
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
	{% endfor %}
	{% endfor %}
	{% endif %}
	<div class="row">
		<div class="col-lg-6 offset-lg-3">
			<form action="{{ url_for('auth.login_account') }}" method="post">
				{{ form.csrf_token }}
				<div class="form-group form-box">
					{{ render_field(form.email, class_="form-control") }}
				</div>
				<div class="form-group form-box">
					{{ render_field(form.password, class_="form-control") }}
				</div>
				<div class="form-group text-center">
					<input type="submit" class="btn btn-primary" value="Login">
				</div>
			</form>
		</div>
	</div>
	
	<div class="row text-center pt-3">
		<div class="col-lg-6 offset-lg-3">
			<a href="{{url_for('auth.register_account')}}">Don’t have an account? Register here.</a>
		</div>
		<div class="w-100"></div>
		<div class="col-lg-6 offset-lg-3">
			<a href="{{url_for('auth.forget_password_request')}}">Forgot your password? Reset here.</a>			
		</div>
	</div>
</div>

{% endblock content %}

main/website/templates/loginpage.html
{% extends "includes/layout.html" %}

{% block title %}Login{% endblock title %}

{% block page_name %}
Login
{% endblock page_name %}

{% block content %}
<div class="container pt-5">
	{% from "includes/formhelper.html" import render_field %}
	{% if form.errors %}
	{% for field_name, field_errors in form.errors|dictsort if field_errors %}
	{% for error in field_errors %}
	<div class="alert alert-danger alert-dismissible fade show" role="alert">
		{{ form[field_name].label }}: {{ error }}
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
	{% endfor %}
	{% endfor %}
	{% endif %}
	<div class="row">
		<div class="col-lg-6 offset-lg-3">
			<form action="{{ url_for('auth.login_account') }}" method="post">
				{{ form.csrf_token }}
				<div class="form-group form-box">
					{{ render_field(form.email, class_="form-control") }}
				</div>
				<div class="form-group form-box">
					{{ render_field(form.password, class_="form-control") }}
				</div>
				<div class="form-group text-center">
					<input type="submit" class="btn btn-primary" value="Login">
				</div>
			</form>
		</div>
	</div>
	
	<div class="row text-center pt-3">
		<div class="col-lg-6 offset-lg-3">
			<a href="{{url_for('auth.register_account')}}">Don’t have an account? Register here.</a>
		</div>
		<div class="w-100"></div>
		<div class="col-lg-6 offset-lg-3">
			<a href="{{url_for('auth.forget_password_request')}}">Forgot your password? Reset here.</a>			
		</div>
	</div>
</div>

{% endblock content %}

main/website/templates/manage_property_page.html
{% extends "includes/layout.html" %}

{% block title %}Manage Properties{% endblock title %}

{% block page_name %}
Manage Properties
{% endblock page_name %}

{% block content %}
{% from "includes/pagination.html" import render_pagination %}
<div class="container pt-5">
    <div class="row pb-2">
        <div class="col-sm-12 text-center">
            <a href="{{ url_for('views.manage_property_approved') }}" class="btn btn-primary {% if approved %}active{% endif %}">Approved Properties</a>
            <a href="{{ url_for('views.manage_property_unapproved') }}" class="btn btn-primary {% if not approved and not deletion%}active{% endif %}">Unapproved Properties</a>
            <a href="{{ url_for('views.manage_property_pending_deletion') }}" class="btn btn-primary {% if deletion %}active{% endif %}">Properties Pending Deletion</a>
        </div>
    </div>
    <hr>
    {% if property_list.items %}
    {% for property in property_list  %}
    <div class="row pb-2">
        <div class="col-sm-4">
            <img src="{{ url_for('properties_views.property_image_url', filename=property.property_images[0].image_url) }}" class="img-fluid" alt="Responsive image">
        </div>
        <div class="col-sm-8">
            <div class="row">
                <div class="col-12">
                    <h2>
                        {% if approved %}
                            <a href="{{ url_for('properties_views.map_page_info',property_id=property.property_id) }}">{{ property.property_name }}</a>
                        {% else %}
                            {{ property.property_name }}
                        {% endif %}
                    </h2>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <h3>${{ property.monthly_rent }}/month</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <p>{{ property.description }}</p>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <p>{{ property.block }} {{ property.street_name }} 
                    <p class="card-text">{{property.block}} {{ property.street_name }} {% if property.building != 'NIL' %}
                        {{ property.building }}
                    {% endif %}</p>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <p>Singapore {{ property.postal }}</p>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    {% if not deletion %}
                       <a href="{{ url_for('views.edit_property', prop_id=property.property_id) }}" class="btn btn-primary">Edit</a> 
                       <a href="{{ url_for('views.delete_property', prop_id=property.property_id) }}" class="btn btn-danger">Delete</a> 
                    {% else %}
                        <form action="{{ url_for('views.cancel_deletion', prop_id=property.property_id) }}" method="post">
                            <button type="submit" class="btn btn-danger">Cancel Deletion</button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <hr>
    {% endfor %}
    <div class="col-12">
        {% if approved %}
        {{ render_pagination(property_list, 'views.manage_property_approved') }}    
        {% elif deletion %}
        {{ render_pagination(property_list, 'views.manage_property_pending_deletion') }}   
        {% else %}
        {{ render_pagination(property_list, 'views.manage_property_unapproved') }}
        {% endif %}
    </div>
    {% else %}
    {% if not deletion %}
    <div class="col-12">
        <div class="alert alert-info" role="alert">
            <h4 class="alert-heading">No properties</h4>
            <p>You have no properties. Start uploading one <a href='{{ url_for("views.register_property") }}'>here</a>.</p>
        </div>
    </div>
    {% else %}
    <div class="col-12">
        <div class="alert alert-info" role="alert">
            <h4 class="alert-heading">No properties</h4>
            <p>You have no properties pending deletion.</p>
        </div>
    </div>
    {% endif %}

    {% endif %}
</div>
{% endblock content %}