main/website/routers/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from .. import forms, db
from flask_login import login_user, login_required, logout_user, current_user
from ..models import User, AccountRecovery

auth = Blueprint('auth',__name__)

@auth.route("/login", methods=["GET","POST"])
def login_account():
    form = forms.LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user)
                return redirect(url_for("properties_views.map_page"))
            else:
                flash('Incorrect email or password', category='error')
        else:
            flash('Incorrect email or password', category='error')
        
    return render_template("login_page.html", user=current_user, form=form)

@auth.route("/logout")
@login_required
def logout_account():
    logout_user()
    return redirect(url_for("auth.login_account"))

@auth.route("/register", methods=["GET","POST"])
def register_account():
    form = forms.RegistrationForm()
    if form.validate_on_submit():
        email = form.email.data
        user = User.query.filter_by(email=email).first()
        if user:
            flash("Email: Email is already taken",category='error')
        else:
            password = generate_password_hash(form.password.data) #123456789aA$ , 123456789aA$$

            new_user = User(email=email, 
                            password=password, 
                            username=email.split("@")[0], 
                            account_type=form.register_as.data,
                            first_name=form.first_name.data,
                            last_name=form.last_name.data)
            
            User.register_account(new_user)

            flash(f"Registered as a {str(form.register_as.data).title()} Successfully", category='success')
            return redirect(url_for('auth.login_account'))
        
    return render_template("register_account_page.html", user=current_user, form=form)

@auth.route('/forgetpassword', methods=['GET', 'POST'])
def forget_password_request():
    form = forms.ForgetPasswordForm()
    if form.validate_on_submit():
        email = form.email.data
        user = User.query.filter_by(email=email).first()

        if user:
            flash_msg = AccountRecovery.create_and_send_account_recovery(user, request.url_root)

            flash(flash_msg[0], flash_msg[1])

            return redirect(url_for("auth.login_account"))
        else:
            flash("There are no accounts with this email", 'error')
            return redirect(url_for("auth.forget_password_request"))
        
    return render_template("forget_password_request_page.html", user=current_user, form=form)


@auth.route('/forgetpassword/<uuid:reset_id>', methods=["GET", "POST"])
def forget_password(reset_id):
    form = forms.ChangeForgetPasswordForm()

    valid_request = AccountRecovery.check_valid_recovery_string(str(reset_id))

    if not valid_request[0]:
        flash(valid_request[1], valid_request[2])
        return redirect(url_for("auth.forget_password_request"))
    else:
        if form.validate_on_submit():
            account_recovery = valid_request[1]
            user_id = account_recovery.user_id
            user = User.query.filter_by(user_id=user_id).first()

            password = generate_password_hash(form.password.data)
            user.password = password

            db.session.delete(account_recovery)

            db.session.commit()
            flash("Password changed successfully")
            return redirect(url_for("auth.login_account"))
    return render_template("forget_password_change_page.html", user=current_user, form=form, reset_id=reset_id)

@auth.route('/page404')
def page404():
    return render_template("404.html", user=current_user)

main/website/routers/views.py
import os.path

from flask import Blueprint, render_template, url_for, flash, redirect, request, current_app
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename

from .custom_decorators import landlord_required
from .. import forms, db, models
from ..models import Property, PropertyImages, Notifications, User
from datetime import datetime
import requests
from werkzeug.security import check_password_hash


views = Blueprint('views', __name__)

@views.route("/")
def landing_page():
    latest_properties = Property.query.filter_by(is_approved=1).order_by(Property.created_at.desc()).limit(3).all()

    return render_template("landing_page.html", user=current_user, latest_properties=latest_properties, datetime_now = datetime.now())


APPROVAL_FORM_ALLOWED_EXTENSIONS = {"pdf"}
IMAGES_ALLOWED_EXTENSIONS = {"png"}


def allowed_file(filename, allowed_extensions):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in allowed_extensions

@views.route("/manage_property/approved")
@login_required
@landlord_required
def manage_property_approved():
    # get all properties owned by user
    property_list = db.paginate(db.select(Property).where(Property.user_id == current_user.user_id, Property.is_approved==True).order_by(Property.created_at.desc()), per_page=10)
    if request.args.get('page'):
        property_list = db.paginate(db.select(Property).where(Property.user_id == current_user.user_id, Property.is_approved==True).order_by(Property.created_at.desc()), per_page=10, page=int(request.args.get('page')))
    print(property_list)
    return render_template("manage_property_page.html", user=current_user, property_list=property_list, approved=True, deletion=False)

@views.route("/manage_property/unapproved")
@login_required
@landlord_required
def manage_property_unapproved():
    # get all properties owned by user
    property_list = db.paginate(db.select(Property).where(Property.user_id == current_user.user_id, Property.is_approved==False).order_by(Property.created_at.desc()), per_page=10)
    if request.args.get('page'):
        property_list = db.paginate(db.select(Property).where(Property.user_id == current_user.user_id, Property.is_approved==False).order_by(Property.created_at.desc()), per_page=10, page=int(request.args.get('page')))

    return render_template("manage_property_page.html", user=current_user, property_list=property_list, approved=False, deletion=False)


@views.route("/manage_property/pending_deletion")
@login_required
@landlord_required
def manage_property_pending_deletion():
    # get all properties owned by user
    property_list = db.paginate(db.select(Property).where(Property.user_id == current_user.user_id, Property.is_pending_deletion==True).order_by(Property.created_at.desc()), per_page=10)
    if request.args.get('page'):
        property_list = db.paginate(db.select(Property).where(Property.user_id == current_user.user_id, Property.is_pending_deletion==True).order_by(Property.created_at.desc()), per_page=10, page=int(request.args.get('page')))

    return render_template("manage_property_page.html", user=current_user, property_list=property_list, approved=False, deletion=True)

@views.route("/manage_property/registerproperty", methods=["GET", "POST"])
@login_required
@landlord_required
def register_property():
    form = forms.RegisterPropertyForm()

    if form.validate_on_submit():
        # check if the approval form is the correct type
        approval_form_filename = secure_filename(form.approval_form.name)  # get the file name from the form
        approval = request.files[approval_form_filename]  # get the filestorage object

        if approval.filename == "":  # empty file name, no file selected
            flash("No approval file selected", "error")
            return redirect(url_for('views.register_property'))

        if not allowed_file(approval.filename, APPROVAL_FORM_ALLOWED_EXTENSIONS):  # check if file is pdf type
            flash("Invalid approval file type, only .pdf files are allowed", "error")
            return redirect(url_for('views.register_property'))

        # do the same check for image(multiple images can be uploaded)
        for i, image in enumerate(form.image.data):
            if i > 5:
                flash("Max of 5 images are allowed", "error")
                return redirect(url_for('views.register_property'))

            if not allowed_file(secure_filename(image.filename),
                                IMAGES_ALLOWED_EXTENSIONS):  # check if file is png type
                flash("Invalid image file type, only .png files are allowed", "error")
                return redirect(url_for('views.register_property'))

        postal_code = form.postal_code.data
        url = f"https://www.onemap.gov.sg/api/common/elastic/search?searchVal={postal_code}&returnGeom=Y&getAddrDetails=Y&pageNum=1"
        response = requests.request("GET", url)
        response = response.json()
        # sanity check, if the response["results"] has length 0, it means no address is returned
        if len(response["results"]) == 0:
            flash("Invalid postal code", "error")
            return redirect(url_for('views.register_property'))
        result_dict = response["results"][0]
        property_latitude = result_dict['LATITUDE']
        property_longitude = result_dict['LONGITUDE']
        property_streetname = result_dict['ROAD_NAME']
        property_building = result_dict['BUILDING'] #if result_dict['BUILDING'] != 'NIL' else result_dict['BLK_NO'] # some properties are using NIL as building name in the csv file, keep it as it is
        property_block = result_dict['BLK_NO']

        new_property = models.Property(user_id=current_user.user_id,
                                       #rent_approval_date=form.rent_approval_date.data, # set approval date only when admin approves
                                       town=form.town.data,
                                       block=property_block,
                                       street_name=property_streetname,
                                       flat_type=form.flat_type.data,
                                       monthly_rent=form.monthly_rent.data,
                                       postal=form.postal_code.data,
                                       latitude=property_latitude,
                                       longitude=property_longitude,
                                       building=property_building,
                                       number_of_bedrooms=form.num_bedrooms.data,
                                       floorsize=form.floor_size.data,
                                       price_per_square_metre=round(form.monthly_rent.data / form.floor_size.data, 6),
                                       year_built=form.year_built.data,
                                       floor_level=form.floor_level.data,
                                       furnishing=form.furnishing.data,
                                       lease_term=form.lease_term.data,
                                       negotiable_pricing=form.negotiable.data,
                                       property_name=form.property_name.data,
                                       property_description=form.property_description.data,
                                       gender=form.gender.data)
        db.session.add(new_property)
        db.session.commit()
        db.session.refresh(new_property)

        property_id = new_property.property_id

        reformatted_filename = f"{property_id}"

        # save the approval form to the respective folder
        approval_form_file_path = os.path.join(current_app.config["APPROVAL_DOCUMENT_UPLOAD_FOLDER"], reformatted_filename + ".pdf")
        approval.save(approval_form_file_path)
        new_property.approval_document_url = reformatted_filename + ".pdf"
        db.session.commit()

        # save the image(s) to the respective folder and add it into the property_image database
        # image_url in the property_image database will store all images separated by a comma
        for i, image in enumerate(form.image.data):
            image_form_file_path = os.path.join(current_app.config["IMAGE_UPLOAD_FOLDER"], reformatted_filename + f"_{i}.png")
            image.save(image_form_file_path)
            new_property_image = PropertyImages(property_id=property_id,
                                                image_url=reformatted_filename+f"_{i}.png")
            db.session.add(new_property_image)
            db.session.commit()
        flash("Property registered, pending approval", "success")
        return redirect(url_for('views.manage_property_unapproved'))

    return render_template("register_property.html", user=current_user, form=form)

@views.route("/manage_property/edit_property/<prop_id>", methods=["GET", "POST"])
@login_required
@landlord_required
def edit_property(prop_id):
    form = forms.EditProperty()
    # get the property with prop_id and prefill in the form with previous information
    current_property = Property.query.filter_by(property_id=prop_id).first()

    if request.method == "GET":
        # prefill the form
        form.property_name.data = current_property.property_name
        form.monthly_rent.data = current_property.monthly_rent
        form.num_bedrooms.data = current_property.number_of_bedrooms
        form.gender.data = current_property.gender
        form.furnishing.data = current_property.furnishing
        form.lease_term.data = current_property.lease_term
        form.negotiable.data = current_property.negotiable_pricing
        form.property_description.data = current_property.property_description
    else: # POST
        # edit property
        if form.validate_on_submit() and form.edit_property_button.data:

            # redirect user if wrong password
            if not check_password_hash(current_user.password, form.confirm_password.data):

main/website/templates/includes/formhelper.html
{% macro render_field(field) %}
  {{ field.label(class_="form-label") }}
   <div class="">
       {{ field(**kwargs)|safe }}
   </div>
{% endmacro %}

main/website/templates/includes/layout.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock title %}</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
	<link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.css" rel="stylesheet"/>
	<link href='https://fonts.googleapis.com/css?family=Yesteryear' rel='stylesheet'>
	<!-- <link href="../static/css/style.css" rel="stylesheet"/> -->
	<link href="{{url_for('static', filename='css/extra.css') }}" rel="stylesheet"/>
	<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
	<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
	<script src="https://kit.fontawesome.com/a23fea9039.js" crossorigin="anonymous"></script>
	{% block head_block %}{% endblock head_block %}
	<style>
		.header-img{
			background-image: url("{{url_for('static', filename='images/Header-blurred.png') }}");
			background-repeat: no-repeat;
			background-size: cover;
			background-position: center;
			height: 400px;
			width: 100%;
			position: relative;
		}
	</style>
</head>
<body>
	<div class="header-img">
		<div class="container">
			<nav class="navbar navbar-expand-lg">
				<div class="container-fluid">
					<a class="navbar-brand" href="{{ url_for('views.landing_page') }}">
						<img src="{{url_for('static', filename='images/logo.png') }}" class="img-fluid"/>
					</a>
					<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarNav">
						{% if user.is_authenticated %}
						<ul class="navbar-nav ms-auto mb-2 mb-lg-0 text-center">
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="notifDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
									<i class="fa-solid fa-clipboard-check"></i>
									Actions
								</a>
								<ul class="dropdown-menu" aria-labelledby="notifDropdown">
									<li class="dropdown-item">Notifications:</li>
									<li><hr class="dropdown-divider"></li>
										{% if user.notifications %}
										{% for notif in user.notifications|reverse %}
										{% if loop.index0<3 %}
										<li class="dropdown-item notif-msg" style="cursor: pointer;">{{ notif.title }} <br> {{ notif.created_at.strftime('%d %b %Y %H:%M') }}</li>
										{% endif %}
										{% endfor %}
										{% else %}
										
										<li class="dropdown-item">- None -</li>
										
										{% endif %}
									</li>
									<li><hr class="dropdown-divider"></li>
									<li><a class='dropdown-item' href="{{ url_for('account_views.notifications_page') }}">View all notifications</a></li>
									
									{% if user.account_type == "admin" %}
									<li><hr class="dropdown-divider"></li>
									<li>
										<a class="dropdown-item" href="{{ url_for('admin.admin_panel') }}">Admin Panel</a>
									</li>
									{% endif %}
								</ul>
							</li>
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
									Account
								</a>
								<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
									<li><a class="dropdown-item" href="{{ url_for('properties_views.favourited_properties') }}">Favourites</a></li> 
									<li><hr class="dropdown-divider"></li>
									<li><a class="dropdown-item" href="{{ url_for('account_views.account_settings') }}">Settings</a></li>
									
								</ul>
							</li>
							
							{% if user.account_type == "landlord" %}
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
									Property
								</a>
								<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
									<li><a class="dropdown-item" href="{{ url_for('views.register_property') }}">Register Property</a></li> 
									<li><hr class="dropdown-divider"></li>
									<li><a class="dropdown-item" href="{{ url_for('views.manage_property_approved') }}">Manage Property</a></li>
								</ul>
							</li>
							{% endif %}	
							<li class="nav-item">
								<a class="nav-link" href="{{ url_for('properties_views.map_page') }}">Map</a>
							</li>
						</ul>
						<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
							<li class="nav-item">
								<a class="nav-link nav-button" href="{{ url_for('auth.logout_account') }}">Logout</a>
							</li>
						</ul>
						{% else %}
						<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
							<li class="nav-item">
								<a class="nav-link nav-button" href="{{ url_for('auth.login_account') }}">Login</a>
							</li>
							<li class="nav-item">
								<a class="nav-link nav-button" href="{{ url_for('auth.register_account') }}">Register</a>
							</li>		
						</ul>
						{% endif %}    
					</div>
				</div>
			</nav>
		</div>
		<div class="container d-flex justify-content-center align-content-center pt-5">
			<h1 class="header-text" style="font-family: 'Yesteryear'; font-size: 80px; ">{% block page_name %}{% endblock page_name %}</h1>
		</div>
	</div>
	{% with messages = get_flashed_messages(with_categories=true) %}
	{% if messages %}
	{% for category, message in messages %}
	{% if category == 'error' %}
	<div class="alert alert-danger alert-dismissible fade show" role="alert">
		{{ message }}
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
	{% else %}
	<div class="alert alert-success alert-dismissible fade show" role="alert">
		{{ message }}
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
	{% endif %}
	{% endfor %}
	{% endif %}
	{% endwith %}
	{% block content %}
	
	{% endblock content %}
	
	<div class="container">
		<footer class="row py-5 my-5 border-top">
			<div class="text-center">
				<a href="{{ url_for('views.landing_page') }}" class="text-decoration-none">
					<img src="{{url_for('static', filename='images/logo_black.png') }}" class="img-fluid"/>
				</a>
				<p class="text-body-secondary">Flat rental has never been easier</p>
			</div>
			
			<!-- <div class="col mb-3">
				<h5>Company</h5>
				<ul class="nav flex-column">
					<li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About Us</a></li>
					<li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Careers</a></li>
					<li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Blog</a></li>
					<li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
				</ul>
			</div>
			
			<div class="col mb-3">
				<h5>Locations</h5>
				<ul class="nav flex-column">
					<li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">North</a></li>
					<li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">South</a></li>
					<li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">East</a></li>
					<li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">West</a></li>
				</ul>
			</div>
			
			<div class="col mb-3">
				<form>
					<h5>Subscribe to our newsletter</h5>
					<p>Monthly digest of what's new and exciting from us.</p>
					<div class="d-flex flex-column flex-sm-row w-100 gap-2">
						<label for="newsletter1" class="visually-hidden">Email address</label>
						<input id="newsletter1" type="text" class="form-control" placeholder="Email address">
						<button class="btn btn-primary" type="button">Subscribe</button>
					</div>
				</form>
			</div> -->
			
		</footer>
	</div>
	
	{% block bottomScript %}{% endblock bottomScript %}
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
<div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">© 2023 EasyRoom
</div>
</html>

main/website/templates/includes/pagination.html
{% macro render_pagination(pagination, endpoint) %}
<!-- <div class=page-items>
    {{ pagination.first }} - {{ pagination.last }} of {{ pagination.total }}
</div> -->
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% for page in pagination.iter_pages() %}
        {% if page %}
        {% if page != pagination.page %}
        <li class='page-item'><a class='page-link' href="{{ url_for(endpoint, page=page) }}">{{ page }}</a></li>
        {% else %}
        <li class='page-item active'><span class='page-link'>{{ page }}</span></li>
        {% endif %}
        {% else %}
        <span><i class="fa-solid fa-ellipsis"></i></span>
        {% endif %}
        {% endfor %}
    </ul>
</nav>
{% endmacro %}